# .github/workflows/reuse.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check
on: push # yamllint disable-line rule:truthy

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fsfe/reuse-action@v2
